application: wib-asker
version: 1
runtime: go
api_version: go1
instance_class: B1
manual_scaling:
  instances: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /backend/.*
  script: _go_app
  login: required
  secure: always

- url: /.*
  script: _go_app
  secure: always
