application: questions
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /backend/.*
  script: _go_app
  login: required
  secure: always

- url: /.*
  script: _go_app
  secure: always
