application: wib-asker
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2  # default value
  min_pending_latency: 100ms  # default value
  max_pending_latency: 1000ms
  max_concurrent_requests: 80

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /backend/.*
  script: _go_app
  login: required
  secure: always

- url: /.*
  script: _go_app
  secure: always
